"""ClubService interface."""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from .models import Club, ClubMembership
from ..auth.models import ClubRole


@runtime_checkable
class ClubService(Protocol):
    async def create_club(self, owner_id: str, name: str) -> Club: ...
    async def join_by_invite(self, user_id: str, invite_code: str) -> ClubMembership: ...
    async def get_club(self, club_id: str) -> Club: ...
    async def get_user_clubs(self, user_id: str) -> list[Club]: ...
    async def promote_member(self, club_id: str, actor_id: str, target_id: str, role: ClubRole) -> None: ...
    async def block_member(self, club_id: str, actor_id: str, target_id: str) -> None: ...
    async def remove_member(self, club_id: str, actor_id: str, target_id: str) -> None: ...
