"""TableService interface."""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from .models import HandSummary, TableRecord
from poker_engine.engine.models import TableConfig


@runtime_checkable
class TableService(Protocol):
    async def create_table(self, club_id: str, actor_id: str, config: TableConfig) -> TableRecord: ...
    async def get_table(self, table_id: str) -> TableRecord: ...
    async def get_club_table(self, club_id: str) -> TableRecord | None: ...
    async def update_config(self, table_id: str, actor_id: str, config: TableConfig) -> TableRecord: ...
    async def save_hand_summary(self, summary: HandSummary) -> None: ...
    async def get_hand_history(self, table_id: str, limit: int = 50) -> list[HandSummary]: ...
